[2021-12-14 03:52:41,101] {processor.py:163} INFO - Started process (PID=53) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:52:41,103] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-14 03:52:41,104] {logging_mixin.py:109} INFO - [2021-12-14 03:52:41,104] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:52:46,044] {logging_mixin.py:109} INFO - [2021-12-14 03:52:45,999] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-14 03:52:46,078] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:52:46,105] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 5.008 seconds
[2021-12-14 03:53:16,284] {processor.py:163} INFO - Started process (PID=80) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:53:16,285] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-14 03:53:16,286] {logging_mixin.py:109} INFO - [2021-12-14 03:53:16,286] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:53:17,000] {logging_mixin.py:109} INFO - [2021-12-14 03:53:16,992] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-14 03:53:17,015] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:53:17,027] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.745 seconds
[2021-12-14 03:53:47,180] {processor.py:163} INFO - Started process (PID=116) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:53:47,183] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-14 03:53:47,185] {logging_mixin.py:109} INFO - [2021-12-14 03:53:47,184] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:53:49,556] {logging_mixin.py:109} INFO - [2021-12-14 03:53:49,548] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-14 03:53:49,588] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:53:49,603] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.427 seconds
[2021-12-14 03:54:19,843] {processor.py:163} INFO - Started process (PID=144) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:54:19,844] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-14 03:54:19,845] {logging_mixin.py:109} INFO - [2021-12-14 03:54:19,845] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:54:20,437] {logging_mixin.py:109} INFO - [2021-12-14 03:54:20,427] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-14 03:54:20,451] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:54:20,457] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.617 seconds
[2021-12-14 03:54:50,601] {processor.py:163} INFO - Started process (PID=172) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:54:50,603] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-14 03:54:50,604] {logging_mixin.py:109} INFO - [2021-12-14 03:54:50,604] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:54:51,190] {logging_mixin.py:109} INFO - [2021-12-14 03:54:51,179] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-14 03:54:51,205] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:54:51,212] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.614 seconds
[2021-12-14 03:55:21,365] {processor.py:163} INFO - Started process (PID=210) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:55:21,366] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-14 03:55:21,368] {logging_mixin.py:109} INFO - [2021-12-14 03:55:21,367] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:55:22,214] {logging_mixin.py:109} INFO - [2021-12-14 03:55:22,208] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-14 03:55:22,298] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:55:22,304] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.943 seconds
[2021-12-14 03:55:52,416] {processor.py:163} INFO - Started process (PID=239) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:55:52,417] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-14 03:55:52,418] {logging_mixin.py:109} INFO - [2021-12-14 03:55:52,418] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:55:53,316] {logging_mixin.py:109} INFO - [2021-12-14 03:55:53,310] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-14 03:55:53,329] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-14 03:55:53,336] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.924 seconds
