[2021-12-12 00:00:15,488] {processor.py:163} INFO - Started process (PID=30660) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:00:15,491] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:00:15,493] {logging_mixin.py:109} INFO - [2021-12-12 00:00:15,492] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:00:16,961] {logging_mixin.py:109} INFO - [2021-12-12 00:00:16,949] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:00:16,986] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:00:16,996] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.515 seconds
[2021-12-12 00:00:47,534] {processor.py:163} INFO - Started process (PID=30688) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:00:47,541] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:00:47,546] {logging_mixin.py:109} INFO - [2021-12-12 00:00:47,546] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:00:48,829] {logging_mixin.py:109} INFO - [2021-12-12 00:00:48,813] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:00:48,861] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:00:48,873] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.352 seconds
[2021-12-12 00:01:19,191] {processor.py:163} INFO - Started process (PID=30716) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:01:19,196] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:01:19,199] {logging_mixin.py:109} INFO - [2021-12-12 00:01:19,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:01:20,512] {logging_mixin.py:109} INFO - [2021-12-12 00:01:20,484] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:01:20,558] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:01:20,579] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.399 seconds
[2021-12-12 00:01:50,829] {processor.py:163} INFO - Started process (PID=30745) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:01:50,831] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:01:50,833] {logging_mixin.py:109} INFO - [2021-12-12 00:01:50,832] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:01:52,063] {logging_mixin.py:109} INFO - [2021-12-12 00:01:52,050] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:01:52,087] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:01:52,100] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.275 seconds
[2021-12-12 00:02:22,364] {processor.py:163} INFO - Started process (PID=30783) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:02:22,367] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:02:22,369] {logging_mixin.py:109} INFO - [2021-12-12 00:02:22,368] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:02:23,516] {logging_mixin.py:109} INFO - [2021-12-12 00:02:23,499] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:02:23,550] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:02:23,566] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.208 seconds
[2021-12-12 00:02:53,836] {processor.py:163} INFO - Started process (PID=30802) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:02:53,842] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:02:53,848] {logging_mixin.py:109} INFO - [2021-12-12 00:02:53,847] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:02:54,967] {logging_mixin.py:109} INFO - [2021-12-12 00:02:54,955] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:02:54,991] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:02:55,005] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.186 seconds
[2021-12-12 00:03:25,278] {processor.py:163} INFO - Started process (PID=30841) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:03:25,281] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:03:25,283] {logging_mixin.py:109} INFO - [2021-12-12 00:03:25,283] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:03:26,593] {logging_mixin.py:109} INFO - [2021-12-12 00:03:26,582] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:03:26,615] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:03:26,626] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.357 seconds
[2021-12-12 00:03:56,827] {processor.py:163} INFO - Started process (PID=30870) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:03:56,829] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:03:56,831] {logging_mixin.py:109} INFO - [2021-12-12 00:03:56,831] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:03:58,597] {logging_mixin.py:109} INFO - [2021-12-12 00:03:58,576] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:03:58,640] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:03:58,659] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.838 seconds
[2021-12-12 00:04:28,870] {processor.py:163} INFO - Started process (PID=30900) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:04:28,872] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:04:28,874] {logging_mixin.py:109} INFO - [2021-12-12 00:04:28,874] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:04:30,009] {logging_mixin.py:109} INFO - [2021-12-12 00:04:29,999] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:04:30,032] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:04:30,045] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.181 seconds
[2021-12-12 00:05:00,144] {processor.py:163} INFO - Started process (PID=30927) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:05:00,147] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:05:00,149] {logging_mixin.py:109} INFO - [2021-12-12 00:05:00,149] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:05:01,296] {logging_mixin.py:109} INFO - [2021-12-12 00:05:01,285] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:05:01,319] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:05:01,330] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.198 seconds
[2021-12-12 00:05:31,831] {processor.py:163} INFO - Started process (PID=30955) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:05:31,834] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:05:31,836] {logging_mixin.py:109} INFO - [2021-12-12 00:05:31,836] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:05:33,130] {logging_mixin.py:109} INFO - [2021-12-12 00:05:33,116] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:05:33,160] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:05:33,182] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.359 seconds
[2021-12-12 00:06:03,417] {processor.py:163} INFO - Started process (PID=30985) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:06:03,419] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:06:03,421] {logging_mixin.py:109} INFO - [2021-12-12 00:06:03,420] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:06:04,407] {logging_mixin.py:109} INFO - [2021-12-12 00:06:04,394] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:06:04,435] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:06:04,450] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.038 seconds
[2021-12-12 00:06:34,730] {processor.py:163} INFO - Started process (PID=31013) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:06:34,734] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:06:34,736] {logging_mixin.py:109} INFO - [2021-12-12 00:06:34,736] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:06:36,006] {logging_mixin.py:109} INFO - [2021-12-12 00:06:35,985] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:06:36,044] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:06:36,064] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.344 seconds
[2021-12-12 00:07:06,299] {processor.py:163} INFO - Started process (PID=31041) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:07:06,301] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:07:06,303] {logging_mixin.py:109} INFO - [2021-12-12 00:07:06,302] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:07:07,352] {logging_mixin.py:109} INFO - [2021-12-12 00:07:07,341] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:07:07,378] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:07:07,390] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.097 seconds
[2021-12-12 00:07:37,590] {processor.py:163} INFO - Started process (PID=31070) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:07:37,595] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:07:37,598] {logging_mixin.py:109} INFO - [2021-12-12 00:07:37,598] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:07:39,154] {logging_mixin.py:109} INFO - [2021-12-12 00:07:39,132] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:07:39,205] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:07:39,227] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.654 seconds
[2021-12-12 00:08:09,522] {processor.py:163} INFO - Started process (PID=31099) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:08:09,527] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:08:09,530] {logging_mixin.py:109} INFO - [2021-12-12 00:08:09,529] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:08:10,965] {logging_mixin.py:109} INFO - [2021-12-12 00:08:10,937] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:08:11,020] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:08:11,044] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.533 seconds
[2021-12-12 00:08:41,177] {processor.py:163} INFO - Started process (PID=31128) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:08:41,181] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:08:41,185] {logging_mixin.py:109} INFO - [2021-12-12 00:08:41,184] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:08:42,925] {logging_mixin.py:109} INFO - [2021-12-12 00:08:42,897] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:08:42,985] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:08:43,005] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.842 seconds
[2021-12-12 00:09:13,428] {processor.py:163} INFO - Started process (PID=31157) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:09:13,433] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:09:13,435] {logging_mixin.py:109} INFO - [2021-12-12 00:09:13,435] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:09:15,053] {logging_mixin.py:109} INFO - [2021-12-12 00:09:15,042] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:09:15,072] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:09:15,082] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.665 seconds
[2021-12-12 00:09:45,341] {processor.py:163} INFO - Started process (PID=31185) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:09:45,345] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:09:45,348] {logging_mixin.py:109} INFO - [2021-12-12 00:09:45,348] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:09:46,977] {logging_mixin.py:109} INFO - [2021-12-12 00:09:46,949] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:09:47,004] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:09:47,018] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.689 seconds
[2021-12-12 00:10:17,276] {processor.py:163} INFO - Started process (PID=31214) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:10:17,281] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:10:17,284] {logging_mixin.py:109} INFO - [2021-12-12 00:10:17,284] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:10:19,229] {logging_mixin.py:109} INFO - [2021-12-12 00:10:19,202] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:10:19,280] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:10:19,302] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.038 seconds
[2021-12-12 00:10:50,087] {processor.py:163} INFO - Started process (PID=31242) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:10:50,089] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:10:50,091] {logging_mixin.py:109} INFO - [2021-12-12 00:10:50,091] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:10:51,350] {logging_mixin.py:109} INFO - [2021-12-12 00:10:51,340] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:10:51,375] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:10:51,389] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.308 seconds
[2021-12-12 00:11:21,580] {processor.py:163} INFO - Started process (PID=31271) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:11:21,582] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:11:21,584] {logging_mixin.py:109} INFO - [2021-12-12 00:11:21,584] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:11:22,988] {logging_mixin.py:109} INFO - [2021-12-12 00:11:22,975] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:11:23,010] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:11:23,020] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.445 seconds
[2021-12-12 00:11:53,237] {processor.py:163} INFO - Started process (PID=31300) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:11:53,241] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:11:53,243] {logging_mixin.py:109} INFO - [2021-12-12 00:11:53,242] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:11:54,885] {logging_mixin.py:109} INFO - [2021-12-12 00:11:54,870] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:11:54,913] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:11:54,926] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.696 seconds
[2021-12-12 00:12:25,172] {processor.py:163} INFO - Started process (PID=31329) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:12:25,181] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:12:25,185] {logging_mixin.py:109} INFO - [2021-12-12 00:12:25,184] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:12:26,854] {logging_mixin.py:109} INFO - [2021-12-12 00:12:26,835] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:12:26,889] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:12:26,903] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.746 seconds
[2021-12-12 00:12:57,216] {processor.py:163} INFO - Started process (PID=31356) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:12:57,236] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:12:57,239] {logging_mixin.py:109} INFO - [2021-12-12 00:12:57,239] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:12:58,978] {logging_mixin.py:109} INFO - [2021-12-12 00:12:58,965] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:12:59,009] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:12:59,024] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.824 seconds
[2021-12-12 00:13:29,280] {processor.py:163} INFO - Started process (PID=31385) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:13:29,284] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:13:29,286] {logging_mixin.py:109} INFO - [2021-12-12 00:13:29,286] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:13:30,504] {logging_mixin.py:109} INFO - [2021-12-12 00:13:30,494] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:13:30,527] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:13:30,539] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.269 seconds
[2021-12-12 00:14:00,764] {processor.py:163} INFO - Started process (PID=31425) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:14:00,768] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:14:00,770] {logging_mixin.py:109} INFO - [2021-12-12 00:14:00,770] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:14:02,093] {logging_mixin.py:109} INFO - [2021-12-12 00:14:02,074] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:14:02,130] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:14:02,147] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.392 seconds
[2021-12-12 00:14:32,415] {processor.py:163} INFO - Started process (PID=31452) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:14:32,420] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:14:32,423] {logging_mixin.py:109} INFO - [2021-12-12 00:14:32,423] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:14:33,837] {logging_mixin.py:109} INFO - [2021-12-12 00:14:33,819] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:14:33,907] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:14:33,928] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.527 seconds
[2021-12-12 00:15:04,248] {processor.py:163} INFO - Started process (PID=31480) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:15:04,255] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:15:04,259] {logging_mixin.py:109} INFO - [2021-12-12 00:15:04,259] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:15:05,303] {logging_mixin.py:109} INFO - [2021-12-12 00:15:05,292] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:15:05,327] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:15:05,340] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.106 seconds
[2021-12-12 00:15:35,706] {processor.py:163} INFO - Started process (PID=31509) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:15:35,709] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:15:35,710] {logging_mixin.py:109} INFO - [2021-12-12 00:15:35,710] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:15:36,803] {logging_mixin.py:109} INFO - [2021-12-12 00:15:36,787] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:15:36,831] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:15:36,844] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.143 seconds
[2021-12-12 00:16:06,981] {processor.py:163} INFO - Started process (PID=31536) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:16:06,985] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:16:06,989] {logging_mixin.py:109} INFO - [2021-12-12 00:16:06,989] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:16:08,528] {logging_mixin.py:109} INFO - [2021-12-12 00:16:08,514] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:16:08,554] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:16:08,566] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.596 seconds
[2021-12-12 00:16:38,827] {processor.py:163} INFO - Started process (PID=31563) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:16:38,830] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:16:38,832] {logging_mixin.py:109} INFO - [2021-12-12 00:16:38,832] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:16:39,690] {logging_mixin.py:109} INFO - [2021-12-12 00:16:39,676] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:16:39,715] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:16:39,726] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.907 seconds
[2021-12-12 00:17:09,996] {processor.py:163} INFO - Started process (PID=31592) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:17:09,998] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:17:10,000] {logging_mixin.py:109} INFO - [2021-12-12 00:17:10,000] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:17:11,206] {logging_mixin.py:109} INFO - [2021-12-12 00:17:11,190] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:17:11,233] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:17:11,246] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.256 seconds
[2021-12-12 00:17:41,469] {processor.py:163} INFO - Started process (PID=31621) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:17:41,473] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:17:41,475] {logging_mixin.py:109} INFO - [2021-12-12 00:17:41,475] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:17:42,863] {logging_mixin.py:109} INFO - [2021-12-12 00:17:42,838] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:17:42,920] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:17:42,947] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.486 seconds
[2021-12-12 00:18:13,257] {processor.py:163} INFO - Started process (PID=31649) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:18:13,263] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:18:13,267] {logging_mixin.py:109} INFO - [2021-12-12 00:18:13,267] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:18:14,657] {logging_mixin.py:109} INFO - [2021-12-12 00:18:14,641] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:18:14,689] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:18:14,703] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.462 seconds
[2021-12-12 00:18:45,036] {processor.py:163} INFO - Started process (PID=31678) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:18:45,040] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:18:45,043] {logging_mixin.py:109} INFO - [2021-12-12 00:18:45,043] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:18:46,409] {logging_mixin.py:109} INFO - [2021-12-12 00:18:46,397] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:18:46,432] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:18:46,445] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.424 seconds
[2021-12-12 00:19:16,656] {processor.py:163} INFO - Started process (PID=31707) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:19:16,658] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:19:16,659] {logging_mixin.py:109} INFO - [2021-12-12 00:19:16,659] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:19:17,880] {logging_mixin.py:109} INFO - [2021-12-12 00:19:17,868] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:19:17,920] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:19:17,938] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.286 seconds
[2021-12-12 00:19:48,173] {processor.py:163} INFO - Started process (PID=31736) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:19:48,178] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:19:48,181] {logging_mixin.py:109} INFO - [2021-12-12 00:19:48,181] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:19:49,692] {logging_mixin.py:109} INFO - [2021-12-12 00:19:49,680] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:19:49,720] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:19:49,733] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.570 seconds
[2021-12-12 00:20:19,995] {processor.py:163} INFO - Started process (PID=31765) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:20:19,999] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:20:20,002] {logging_mixin.py:109} INFO - [2021-12-12 00:20:20,001] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:20:21,402] {logging_mixin.py:109} INFO - [2021-12-12 00:20:21,389] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:20:21,430] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:20:21,448] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.462 seconds
[2021-12-12 00:20:51,790] {processor.py:163} INFO - Started process (PID=31801) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:20:51,793] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:20:51,795] {logging_mixin.py:109} INFO - [2021-12-12 00:20:51,795] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:20:53,093] {logging_mixin.py:109} INFO - [2021-12-12 00:20:53,083] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:20:53,119] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:20:53,132] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.350 seconds
[2021-12-12 00:21:23,421] {processor.py:163} INFO - Started process (PID=31830) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:21:23,426] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:21:23,429] {logging_mixin.py:109} INFO - [2021-12-12 00:21:23,428] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:21:24,601] {logging_mixin.py:109} INFO - [2021-12-12 00:21:24,589] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:21:24,622] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:21:24,632] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.223 seconds
[2021-12-12 00:21:54,837] {processor.py:163} INFO - Started process (PID=31858) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:21:54,840] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:21:54,842] {logging_mixin.py:109} INFO - [2021-12-12 00:21:54,842] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:21:56,135] {logging_mixin.py:109} INFO - [2021-12-12 00:21:56,103] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:21:56,191] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:21:56,217] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.388 seconds
[2021-12-12 00:22:26,449] {processor.py:163} INFO - Started process (PID=31887) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:22:26,451] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:22:26,453] {logging_mixin.py:109} INFO - [2021-12-12 00:22:26,452] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:22:27,824] {logging_mixin.py:109} INFO - [2021-12-12 00:22:27,805] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:22:27,857] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:22:27,869] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.425 seconds
[2021-12-12 00:22:58,095] {processor.py:163} INFO - Started process (PID=31915) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:22:58,099] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:22:58,101] {logging_mixin.py:109} INFO - [2021-12-12 00:22:58,101] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:22:59,330] {logging_mixin.py:109} INFO - [2021-12-12 00:22:59,312] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:22:59,360] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:22:59,374] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.287 seconds
[2021-12-12 00:23:29,594] {processor.py:163} INFO - Started process (PID=31943) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:23:29,596] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:23:29,598] {logging_mixin.py:109} INFO - [2021-12-12 00:23:29,598] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:23:30,818] {logging_mixin.py:109} INFO - [2021-12-12 00:23:30,806] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:23:30,845] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:23:30,857] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.270 seconds
[2021-12-12 00:24:01,098] {processor.py:163} INFO - Started process (PID=31971) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:24:01,103] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:24:01,105] {logging_mixin.py:109} INFO - [2021-12-12 00:24:01,105] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:24:02,639] {logging_mixin.py:109} INFO - [2021-12-12 00:24:02,625] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:24:02,661] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:24:02,672] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.585 seconds
[2021-12-12 00:24:32,950] {processor.py:163} INFO - Started process (PID=31999) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:24:32,953] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:24:32,955] {logging_mixin.py:109} INFO - [2021-12-12 00:24:32,955] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:24:34,377] {logging_mixin.py:109} INFO - [2021-12-12 00:24:34,366] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:24:34,401] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:24:34,411] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.471 seconds
[2021-12-12 00:25:04,585] {processor.py:163} INFO - Started process (PID=32026) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:25:04,589] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:25:04,591] {logging_mixin.py:109} INFO - [2021-12-12 00:25:04,590] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:25:06,241] {logging_mixin.py:109} INFO - [2021-12-12 00:25:06,230] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:25:06,262] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:25:06,273] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.694 seconds
[2021-12-12 00:25:36,853] {processor.py:163} INFO - Started process (PID=32055) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:25:36,855] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:25:36,856] {logging_mixin.py:109} INFO - [2021-12-12 00:25:36,856] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:25:38,051] {logging_mixin.py:109} INFO - [2021-12-12 00:25:38,035] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:25:38,137] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:25:38,161] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.312 seconds
[2021-12-12 00:26:08,419] {processor.py:163} INFO - Started process (PID=32082) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:26:08,425] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:26:08,428] {logging_mixin.py:109} INFO - [2021-12-12 00:26:08,427] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:26:10,058] {logging_mixin.py:109} INFO - [2021-12-12 00:26:10,045] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:26:10,095] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:26:10,109] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.702 seconds
[2021-12-12 00:26:40,433] {processor.py:163} INFO - Started process (PID=32110) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:26:40,436] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:26:40,439] {logging_mixin.py:109} INFO - [2021-12-12 00:26:40,439] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:26:41,571] {logging_mixin.py:109} INFO - [2021-12-12 00:26:41,556] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:26:41,599] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:26:41,611] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.189 seconds
[2021-12-12 00:27:11,820] {processor.py:163} INFO - Started process (PID=32139) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:27:11,823] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:27:11,825] {logging_mixin.py:109} INFO - [2021-12-12 00:27:11,824] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:27:12,942] {logging_mixin.py:109} INFO - [2021-12-12 00:27:12,930] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:27:12,969] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:27:12,983] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.171 seconds
[2021-12-12 00:27:43,107] {processor.py:163} INFO - Started process (PID=32168) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:27:43,113] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:27:43,116] {logging_mixin.py:109} INFO - [2021-12-12 00:27:43,116] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:27:44,413] {logging_mixin.py:109} INFO - [2021-12-12 00:27:44,404] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:27:44,438] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:27:44,455] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.362 seconds
[2021-12-12 00:28:14,660] {processor.py:163} INFO - Started process (PID=32196) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:28:14,662] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:28:14,664] {logging_mixin.py:109} INFO - [2021-12-12 00:28:14,664] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:28:16,203] {logging_mixin.py:109} INFO - [2021-12-12 00:28:16,176] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:28:16,252] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:28:16,272] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.617 seconds
[2021-12-12 00:28:46,536] {processor.py:163} INFO - Started process (PID=32223) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:28:46,539] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:28:46,541] {logging_mixin.py:109} INFO - [2021-12-12 00:28:46,541] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:28:48,189] {logging_mixin.py:109} INFO - [2021-12-12 00:28:48,166] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:28:48,234] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:28:48,253] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.725 seconds
[2021-12-12 00:29:18,498] {processor.py:163} INFO - Started process (PID=32251) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:29:18,504] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:29:18,507] {logging_mixin.py:109} INFO - [2021-12-12 00:29:18,506] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:29:19,646] {logging_mixin.py:109} INFO - [2021-12-12 00:29:19,635] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:29:19,669] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:29:19,680] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.193 seconds
[2021-12-12 00:29:49,904] {processor.py:163} INFO - Started process (PID=32280) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:29:49,906] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:29:49,908] {logging_mixin.py:109} INFO - [2021-12-12 00:29:49,908] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:29:51,083] {logging_mixin.py:109} INFO - [2021-12-12 00:29:51,069] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:29:51,114] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:29:51,129] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.232 seconds
[2021-12-12 00:30:21,780] {processor.py:163} INFO - Started process (PID=32307) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:30:21,783] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:30:21,784] {logging_mixin.py:109} INFO - [2021-12-12 00:30:21,784] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:30:22,995] {logging_mixin.py:109} INFO - [2021-12-12 00:30:22,984] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:30:23,018] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:30:23,029] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.255 seconds
[2021-12-12 00:30:53,230] {processor.py:163} INFO - Started process (PID=32334) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:30:53,232] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:30:53,234] {logging_mixin.py:109} INFO - [2021-12-12 00:30:53,233] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:30:54,250] {logging_mixin.py:109} INFO - [2021-12-12 00:30:54,238] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:30:54,272] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:30:54,282] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.057 seconds
[2021-12-12 00:31:24,473] {processor.py:163} INFO - Started process (PID=32362) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:31:24,475] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:31:24,477] {logging_mixin.py:109} INFO - [2021-12-12 00:31:24,477] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:31:25,553] {logging_mixin.py:109} INFO - [2021-12-12 00:31:25,543] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:31:25,579] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:31:25,592] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.123 seconds
[2021-12-12 00:31:55,804] {processor.py:163} INFO - Started process (PID=32389) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:31:55,806] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 00:31:55,808] {logging_mixin.py:109} INFO - [2021-12-12 00:31:55,808] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:31:57,245] {logging_mixin.py:109} INFO - [2021-12-12 00:31:57,223] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 00:31:57,285] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 00:31:57,311] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.515 seconds
[2021-12-12 19:41:31,392] {processor.py:163} INFO - Started process (PID=32449) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:41:31,404] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 19:41:31,417] {logging_mixin.py:109} INFO - [2021-12-12 19:41:31,416] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:41:34,136] {logging_mixin.py:109} INFO - [2021-12-12 19:41:34,079] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 19:41:34,188] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:41:34,228] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.844 seconds
[2021-12-12 19:42:04,697] {processor.py:163} INFO - Started process (PID=32480) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:42:04,700] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 19:42:04,702] {logging_mixin.py:109} INFO - [2021-12-12 19:42:04,702] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:42:06,429] {logging_mixin.py:109} INFO - [2021-12-12 19:42:06,408] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 19:42:06,477] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:42:06,504] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.816 seconds
[2021-12-12 19:42:36,801] {processor.py:163} INFO - Started process (PID=32509) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:42:36,804] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 19:42:36,807] {logging_mixin.py:109} INFO - [2021-12-12 19:42:36,806] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:42:38,419] {logging_mixin.py:109} INFO - [2021-12-12 19:42:38,402] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 19:42:38,455] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:42:38,473] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.679 seconds
[2021-12-12 19:43:08,810] {processor.py:163} INFO - Started process (PID=32528) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:43:08,814] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 19:43:08,816] {logging_mixin.py:109} INFO - [2021-12-12 19:43:08,816] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:43:10,126] {logging_mixin.py:109} INFO - [2021-12-12 19:43:10,113] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 19:43:10,176] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 19:43:10,192] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.389 seconds
[2021-12-12 21:13:49,721] {processor.py:163} INFO - Started process (PID=32568) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 21:13:49,747] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-12 21:13:49,797] {logging_mixin.py:109} INFO - [2021-12-12 21:13:49,797] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 21:14:03,054] {logging_mixin.py:109} INFO - [2021-12-12 21:14:02,831] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-12 21:14:03,631] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-12 21:14:03,895] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 14.218 seconds
