[2021-12-05 00:00:22,845] {processor.py:163} INFO - Started process (PID=17888) to work on /opt/airflow/dags/VegasPipline/__init__.py
[2021-12-05 00:00:22,847] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipline/__init__.py for tasks to queue
[2021-12-05 00:00:22,847] {logging_mixin.py:109} INFO - [2021-12-05 00:00:22,847] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipline/__init__.py
[2021-12-05 00:00:22,922] {logging_mixin.py:109} INFO - Downloading the addresses data...
[2021-12-05 00:00:23,548] {logging_mixin.py:109} INFO - Saving addresses data to a file...
[2021-12-05 00:00:23,557] {logging_mixin.py:109} INFO - [2021-12-05 00:00:23,549] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipline/__init__.py", line 5, in <module>
    from . import extract_crimedata
  File "/opt/airflow/dags/VegasPipline/extract_crimedata.py", line 25, in <module>
    with open(outfile_path, mode='wb') as outfile:
FileNotFoundError: [Errno 2] No such file or directory: 'data/crimedata.geojson'
[2021-12-05 00:00:23,568] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipline/__init__.py
[2021-12-05 00:00:23,572] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipline/__init__.py took 0.729 seconds
