[2021-12-06 22:36:12,519] {processor.py:163} INFO - Started process (PID=97) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:36:12,528] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:36:12,531] {logging_mixin.py:109} INFO - [2021-12-06 22:36:12,530] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:36:15,803] {logging_mixin.py:109} INFO - [2021-12-06 22:36:15,787] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:36:15,846] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:36:15,863] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 3.352 seconds
[2021-12-06 22:36:46,045] {processor.py:163} INFO - Started process (PID=126) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:36:46,059] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:36:46,063] {logging_mixin.py:109} INFO - [2021-12-06 22:36:46,062] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:36:48,157] {logging_mixin.py:109} INFO - [2021-12-06 22:36:48,129] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:36:48,201] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:36:48,220] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.190 seconds
[2021-12-06 22:37:18,415] {processor.py:163} INFO - Started process (PID=153) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:37:18,418] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:37:18,421] {logging_mixin.py:109} INFO - [2021-12-06 22:37:18,420] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:37:19,912] {logging_mixin.py:109} INFO - [2021-12-06 22:37:19,898] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:37:19,949] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:37:19,972] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.565 seconds
[2021-12-06 22:37:50,251] {processor.py:163} INFO - Started process (PID=180) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:37:50,253] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:37:50,255] {logging_mixin.py:109} INFO - [2021-12-06 22:37:50,255] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:37:51,523] {logging_mixin.py:109} INFO - [2021-12-06 22:37:51,510] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:37:51,566] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:37:51,588] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.343 seconds
[2021-12-06 22:38:21,969] {processor.py:163} INFO - Started process (PID=209) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:38:21,974] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:38:21,978] {logging_mixin.py:109} INFO - [2021-12-06 22:38:21,977] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:38:23,618] {logging_mixin.py:109} INFO - [2021-12-06 22:38:23,604] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:38:23,655] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:38:23,677] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.721 seconds
[2021-12-06 22:38:53,958] {processor.py:163} INFO - Started process (PID=237) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:38:53,967] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:38:53,973] {logging_mixin.py:109} INFO - [2021-12-06 22:38:53,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:38:55,709] {logging_mixin.py:109} INFO - [2021-12-06 22:38:55,684] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:38:55,752] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:38:55,777] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.834 seconds
[2021-12-06 22:39:26,067] {processor.py:163} INFO - Started process (PID=265) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:39:26,076] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:39:26,082] {logging_mixin.py:109} INFO - [2021-12-06 22:39:26,080] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:39:28,283] {logging_mixin.py:109} INFO - [2021-12-06 22:39:28,255] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:39:28,383] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:39:28,418] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.365 seconds
[2021-12-06 22:39:58,728] {processor.py:163} INFO - Started process (PID=294) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:39:58,733] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:39:58,736] {logging_mixin.py:109} INFO - [2021-12-06 22:39:58,735] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:40:00,424] {logging_mixin.py:109} INFO - [2021-12-06 22:40:00,411] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:40:00,462] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:40:00,475] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.761 seconds
[2021-12-06 22:40:30,733] {processor.py:163} INFO - Started process (PID=322) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:40:30,735] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:40:30,736] {logging_mixin.py:109} INFO - [2021-12-06 22:40:30,736] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:40:32,116] {logging_mixin.py:109} INFO - [2021-12-06 22:40:32,101] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:40:32,143] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:40:32,155] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.427 seconds
[2021-12-06 22:41:02,398] {processor.py:163} INFO - Started process (PID=350) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:41:02,400] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:41:02,402] {logging_mixin.py:109} INFO - [2021-12-06 22:41:02,402] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:41:03,564] {logging_mixin.py:109} INFO - [2021-12-06 22:41:03,550] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:41:03,595] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:41:03,611] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.218 seconds
[2021-12-06 22:41:34,144] {processor.py:163} INFO - Started process (PID=377) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:41:34,147] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:41:34,149] {logging_mixin.py:109} INFO - [2021-12-06 22:41:34,148] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:41:35,411] {logging_mixin.py:109} INFO - [2021-12-06 22:41:35,394] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:41:35,466] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:41:35,497] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.362 seconds
[2021-12-06 22:42:05,749] {processor.py:163} INFO - Started process (PID=404) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:42:05,754] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:42:05,757] {logging_mixin.py:109} INFO - [2021-12-06 22:42:05,756] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:42:07,479] {logging_mixin.py:109} INFO - [2021-12-06 22:42:07,452] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:42:07,555] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:42:07,576] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.839 seconds
[2021-12-06 22:42:37,723] {processor.py:163} INFO - Started process (PID=432) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:42:37,727] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:42:37,729] {logging_mixin.py:109} INFO - [2021-12-06 22:42:37,728] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:42:39,321] {logging_mixin.py:109} INFO - [2021-12-06 22:42:39,304] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:42:39,352] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:42:39,365] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.649 seconds
[2021-12-06 22:43:09,637] {processor.py:163} INFO - Started process (PID=460) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:43:09,643] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:43:09,647] {logging_mixin.py:109} INFO - [2021-12-06 22:43:09,646] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:43:11,717] {logging_mixin.py:109} INFO - [2021-12-06 22:43:11,698] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:43:11,748] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:43:11,762] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.141 seconds
[2021-12-06 22:43:42,045] {processor.py:163} INFO - Started process (PID=488) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:43:42,049] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:43:42,051] {logging_mixin.py:109} INFO - [2021-12-06 22:43:42,051] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:43:43,467] {logging_mixin.py:109} INFO - [2021-12-06 22:43:43,453] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:43:43,499] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:43:43,522] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.484 seconds
[2021-12-06 22:44:13,986] {processor.py:163} INFO - Started process (PID=517) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:44:13,995] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:44:14,008] {logging_mixin.py:109} INFO - [2021-12-06 22:44:14,008] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:44:16,411] {logging_mixin.py:109} INFO - [2021-12-06 22:44:16,391] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:44:16,452] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:44:16,470] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.494 seconds
[2021-12-06 22:44:46,595] {processor.py:163} INFO - Started process (PID=545) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:44:46,597] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:44:46,599] {logging_mixin.py:109} INFO - [2021-12-06 22:44:46,599] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:44:48,322] {logging_mixin.py:109} INFO - [2021-12-06 22:44:48,304] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:44:48,359] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:44:48,376] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.787 seconds
[2021-12-06 22:45:18,773] {processor.py:163} INFO - Started process (PID=575) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:45:18,779] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:45:18,785] {logging_mixin.py:109} INFO - [2021-12-06 22:45:18,784] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:45:20,361] {logging_mixin.py:109} INFO - [2021-12-06 22:45:20,348] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:45:20,386] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:45:20,398] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.640 seconds
[2021-12-06 22:45:50,643] {processor.py:163} INFO - Started process (PID=610) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:45:50,646] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:45:50,648] {logging_mixin.py:109} INFO - [2021-12-06 22:45:50,648] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:45:51,869] {logging_mixin.py:109} INFO - [2021-12-06 22:45:51,858] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:45:51,893] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:45:51,912] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.277 seconds
[2021-12-06 22:46:22,355] {processor.py:163} INFO - Started process (PID=640) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:46:22,358] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:46:22,360] {logging_mixin.py:109} INFO - [2021-12-06 22:46:22,359] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:46:23,705] {logging_mixin.py:109} INFO - [2021-12-06 22:46:23,690] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:46:23,740] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:46:23,759] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.413 seconds
[2021-12-06 22:46:53,992] {processor.py:163} INFO - Started process (PID=671) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:46:53,995] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:46:53,997] {logging_mixin.py:109} INFO - [2021-12-06 22:46:53,997] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:46:55,178] {logging_mixin.py:109} INFO - [2021-12-06 22:46:55,165] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:46:55,204] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:46:55,220] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.235 seconds
[2021-12-06 22:47:25,432] {processor.py:163} INFO - Started process (PID=698) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:47:25,435] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:47:25,438] {logging_mixin.py:109} INFO - [2021-12-06 22:47:25,437] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:47:26,641] {logging_mixin.py:109} INFO - [2021-12-06 22:47:26,627] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:47:26,667] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:47:26,680] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.256 seconds
[2021-12-06 22:47:56,883] {processor.py:163} INFO - Started process (PID=726) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:47:56,885] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:47:56,886] {logging_mixin.py:109} INFO - [2021-12-06 22:47:56,886] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:47:57,935] {logging_mixin.py:109} INFO - [2021-12-06 22:47:57,925] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:47:57,959] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:47:57,980] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.103 seconds
[2021-12-06 22:48:28,119] {processor.py:163} INFO - Started process (PID=753) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:48:28,122] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:48:28,123] {logging_mixin.py:109} INFO - [2021-12-06 22:48:28,123] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:48:29,472] {logging_mixin.py:109} INFO - [2021-12-06 22:48:29,461] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:48:29,521] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:48:29,540] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.426 seconds
[2021-12-06 22:48:59,761] {processor.py:163} INFO - Started process (PID=782) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:48:59,764] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:48:59,767] {logging_mixin.py:109} INFO - [2021-12-06 22:48:59,766] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:49:01,176] {logging_mixin.py:109} INFO - [2021-12-06 22:49:01,165] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:49:01,200] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:49:01,219] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.469 seconds
[2021-12-06 22:49:31,495] {processor.py:163} INFO - Started process (PID=809) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:49:31,498] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:49:31,500] {logging_mixin.py:109} INFO - [2021-12-06 22:49:31,500] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:49:32,906] {logging_mixin.py:109} INFO - [2021-12-06 22:49:32,891] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:49:32,935] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:49:32,954] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.466 seconds
[2021-12-06 22:50:03,399] {processor.py:163} INFO - Started process (PID=837) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:50:03,406] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:50:03,409] {logging_mixin.py:109} INFO - [2021-12-06 22:50:03,409] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:50:05,051] {logging_mixin.py:109} INFO - [2021-12-06 22:50:05,031] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:50:05,126] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:50:05,148] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.761 seconds
[2021-12-06 22:50:35,427] {processor.py:163} INFO - Started process (PID=865) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:50:35,431] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:50:35,433] {logging_mixin.py:109} INFO - [2021-12-06 22:50:35,432] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:50:36,780] {logging_mixin.py:109} INFO - [2021-12-06 22:50:36,764] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:50:36,826] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:50:36,845] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.426 seconds
[2021-12-06 22:51:07,268] {processor.py:163} INFO - Started process (PID=893) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:51:07,270] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:51:07,272] {logging_mixin.py:109} INFO - [2021-12-06 22:51:07,272] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:51:08,436] {logging_mixin.py:109} INFO - [2021-12-06 22:51:08,422] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:51:08,460] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:51:08,478] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.218 seconds
[2021-12-06 22:51:38,571] {processor.py:163} INFO - Started process (PID=922) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:51:38,573] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:51:38,575] {logging_mixin.py:109} INFO - [2021-12-06 22:51:38,575] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:51:39,730] {logging_mixin.py:109} INFO - [2021-12-06 22:51:39,719] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:51:39,764] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:51:39,784] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.219 seconds
[2021-12-06 22:52:09,845] {processor.py:163} INFO - Started process (PID=950) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:52:09,848] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:52:09,849] {logging_mixin.py:109} INFO - [2021-12-06 22:52:09,849] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:52:11,255] {logging_mixin.py:109} INFO - [2021-12-06 22:52:11,237] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:52:11,280] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:52:11,295] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.456 seconds
[2021-12-06 22:52:41,562] {processor.py:163} INFO - Started process (PID=977) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:52:41,565] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:52:41,566] {logging_mixin.py:109} INFO - [2021-12-06 22:52:41,566] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:52:42,657] {logging_mixin.py:109} INFO - [2021-12-06 22:52:42,644] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:52:42,684] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:52:42,700] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.146 seconds
[2021-12-06 22:53:12,843] {processor.py:163} INFO - Started process (PID=1014) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:53:12,845] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:53:12,847] {logging_mixin.py:109} INFO - [2021-12-06 22:53:12,847] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:53:13,934] {logging_mixin.py:109} INFO - [2021-12-06 22:53:13,922] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:53:13,958] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:53:13,971] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.135 seconds
[2021-12-06 22:53:44,174] {processor.py:163} INFO - Started process (PID=1043) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:53:44,177] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:53:44,179] {logging_mixin.py:109} INFO - [2021-12-06 22:53:44,178] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:53:45,506] {logging_mixin.py:109} INFO - [2021-12-06 22:53:45,493] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:53:45,535] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:53:45,552] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.386 seconds
[2021-12-06 22:54:15,765] {processor.py:163} INFO - Started process (PID=1072) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:54:15,767] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:54:15,768] {logging_mixin.py:109} INFO - [2021-12-06 22:54:15,768] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:54:16,910] {logging_mixin.py:109} INFO - [2021-12-06 22:54:16,899] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:54:16,937] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:54:16,950] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.192 seconds
[2021-12-06 22:54:47,038] {processor.py:163} INFO - Started process (PID=1099) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:54:47,042] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:54:47,044] {logging_mixin.py:109} INFO - [2021-12-06 22:54:47,044] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:54:48,149] {logging_mixin.py:109} INFO - [2021-12-06 22:54:48,135] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:54:48,175] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:54:48,195] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.167 seconds
[2021-12-06 22:55:18,438] {processor.py:163} INFO - Started process (PID=1128) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:55:18,441] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:55:18,443] {logging_mixin.py:109} INFO - [2021-12-06 22:55:18,443] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:55:19,660] {logging_mixin.py:109} INFO - [2021-12-06 22:55:19,646] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:55:19,689] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:55:19,702] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.270 seconds
[2021-12-06 22:55:49,922] {processor.py:163} INFO - Started process (PID=1156) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:55:49,925] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:55:49,927] {logging_mixin.py:109} INFO - [2021-12-06 22:55:49,927] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:55:51,328] {logging_mixin.py:109} INFO - [2021-12-06 22:55:51,314] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:55:51,363] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:55:51,387] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.473 seconds
[2021-12-06 22:56:21,659] {processor.py:163} INFO - Started process (PID=1183) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:56:21,661] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:56:21,663] {logging_mixin.py:109} INFO - [2021-12-06 22:56:21,663] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:56:23,074] {logging_mixin.py:109} INFO - [2021-12-06 22:56:23,052] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:56:23,120] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:56:23,147] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.494 seconds
[2021-12-06 22:56:53,445] {processor.py:163} INFO - Started process (PID=1212) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:56:53,450] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:56:53,456] {logging_mixin.py:109} INFO - [2021-12-06 22:56:53,455] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:56:55,389] {logging_mixin.py:109} INFO - [2021-12-06 22:56:55,352] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:56:55,459] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:56:55,492] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.066 seconds
[2021-12-06 22:57:25,745] {processor.py:163} INFO - Started process (PID=1240) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:57:25,750] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:57:25,754] {logging_mixin.py:109} INFO - [2021-12-06 22:57:25,753] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:57:27,750] {logging_mixin.py:109} INFO - [2021-12-06 22:57:27,718] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:57:27,809] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:57:27,831] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 2.101 seconds
[2021-12-06 22:57:58,071] {processor.py:163} INFO - Started process (PID=1269) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:57:58,073] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:57:58,075] {logging_mixin.py:109} INFO - [2021-12-06 22:57:58,074] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:57:59,329] {logging_mixin.py:109} INFO - [2021-12-06 22:57:59,312] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:57:59,365] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:57:59,385] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.320 seconds
[2021-12-06 22:58:29,636] {processor.py:163} INFO - Started process (PID=1297) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:58:29,639] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:58:29,640] {logging_mixin.py:109} INFO - [2021-12-06 22:58:29,640] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:58:30,967] {logging_mixin.py:109} INFO - [2021-12-06 22:58:30,935] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:58:31,024] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:58:31,056] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.428 seconds
[2021-12-06 22:59:01,299] {processor.py:163} INFO - Started process (PID=1326) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:59:01,303] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:59:01,305] {logging_mixin.py:109} INFO - [2021-12-06 22:59:01,305] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:59:02,528] {logging_mixin.py:109} INFO - [2021-12-06 22:59:02,497] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:59:02,587] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:59:02,616] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.324 seconds
[2021-12-06 22:59:32,945] {processor.py:163} INFO - Started process (PID=1355) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:59:32,949] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 22:59:32,951] {logging_mixin.py:109} INFO - [2021-12-06 22:59:32,951] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:59:34,048] {logging_mixin.py:109} INFO - [2021-12-06 22:59:34,037] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 22:59:34,077] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 22:59:34,096] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.162 seconds
[2021-12-06 23:00:04,221] {processor.py:163} INFO - Started process (PID=1383) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:00:04,225] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:00:04,228] {logging_mixin.py:109} INFO - [2021-12-06 23:00:04,228] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:00:05,456] {logging_mixin.py:109} INFO - [2021-12-06 23:00:05,436] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:00:05,491] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:00:05,513] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.303 seconds
[2021-12-06 23:00:35,747] {processor.py:163} INFO - Started process (PID=1411) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:00:35,749] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:00:35,751] {logging_mixin.py:109} INFO - [2021-12-06 23:00:35,750] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:00:37,532] {logging_mixin.py:109} INFO - [2021-12-06 23:00:37,493] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:00:37,585] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:00:37,612] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.870 seconds
[2021-12-06 23:01:07,878] {processor.py:163} INFO - Started process (PID=1438) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:01:07,880] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:01:07,882] {logging_mixin.py:109} INFO - [2021-12-06 23:01:07,882] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:01:09,061] {logging_mixin.py:109} INFO - [2021-12-06 23:01:09,045] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:01:09,089] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:01:09,108] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.235 seconds
[2021-12-06 23:01:40,167] {processor.py:163} INFO - Started process (PID=1466) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:01:40,172] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:01:40,176] {logging_mixin.py:109} INFO - [2021-12-06 23:01:40,175] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:01:41,769] {logging_mixin.py:109} INFO - [2021-12-06 23:01:41,753] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:01:41,812] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:01:41,836] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.682 seconds
[2021-12-06 23:02:12,081] {processor.py:163} INFO - Started process (PID=1493) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:02:12,083] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:02:12,085] {logging_mixin.py:109} INFO - [2021-12-06 23:02:12,085] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:02:13,442] {logging_mixin.py:109} INFO - [2021-12-06 23:02:13,429] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:02:13,475] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:02:13,497] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.424 seconds
[2021-12-06 23:02:43,634] {processor.py:163} INFO - Started process (PID=1522) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:02:43,640] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:02:43,644] {logging_mixin.py:109} INFO - [2021-12-06 23:02:43,643] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:02:44,831] {logging_mixin.py:109} INFO - [2021-12-06 23:02:44,821] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:02:44,858] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:02:44,876] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.255 seconds
[2021-12-06 23:03:14,960] {processor.py:163} INFO - Started process (PID=1550) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:03:14,964] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:03:14,966] {logging_mixin.py:109} INFO - [2021-12-06 23:03:14,966] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:03:16,689] {logging_mixin.py:109} INFO - [2021-12-06 23:03:16,678] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:03:16,722] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:03:16,736] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.785 seconds
[2021-12-06 23:03:47,052] {processor.py:163} INFO - Started process (PID=1578) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:03:47,057] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:03:47,061] {logging_mixin.py:109} INFO - [2021-12-06 23:03:47,060] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:03:48,478] {logging_mixin.py:109} INFO - [2021-12-06 23:03:48,463] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:03:48,511] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:03:48,526] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.488 seconds
[2021-12-06 23:04:18,712] {processor.py:163} INFO - Started process (PID=1607) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:04:18,715] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:04:18,717] {logging_mixin.py:109} INFO - [2021-12-06 23:04:18,717] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:04:20,089] {logging_mixin.py:109} INFO - [2021-12-06 23:04:20,080] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:04:20,119] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:04:20,132] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.431 seconds
[2021-12-06 23:04:50,440] {processor.py:163} INFO - Started process (PID=1652) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:04:50,448] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:04:50,452] {logging_mixin.py:109} INFO - [2021-12-06 23:04:50,452] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:04:51,711] {logging_mixin.py:109} INFO - [2021-12-06 23:04:51,699] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:04:51,738] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:04:51,749] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.330 seconds
[2021-12-06 23:05:22,056] {processor.py:163} INFO - Started process (PID=1670) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:05:22,061] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:05:22,065] {logging_mixin.py:109} INFO - [2021-12-06 23:05:22,065] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:05:23,527] {logging_mixin.py:109} INFO - [2021-12-06 23:05:23,515] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:05:23,582] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:05:23,595] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.553 seconds
[2021-12-06 23:05:53,920] {processor.py:163} INFO - Started process (PID=1698) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:05:53,923] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:05:53,925] {logging_mixin.py:109} INFO - [2021-12-06 23:05:53,924] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:05:55,374] {logging_mixin.py:109} INFO - [2021-12-06 23:05:55,356] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:05:55,416] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:05:55,431] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.519 seconds
[2021-12-06 23:06:26,054] {processor.py:163} INFO - Started process (PID=1726) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:06:26,057] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:06:26,058] {logging_mixin.py:109} INFO - [2021-12-06 23:06:26,058] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:06:27,292] {logging_mixin.py:109} INFO - [2021-12-06 23:06:27,280] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:06:27,318] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:06:27,330] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.282 seconds
[2021-12-06 23:06:57,595] {processor.py:163} INFO - Started process (PID=1763) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:06:57,598] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:06:57,601] {logging_mixin.py:109} INFO - [2021-12-06 23:06:57,600] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:06:58,650] {logging_mixin.py:109} INFO - [2021-12-06 23:06:58,641] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:06:58,690] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:06:58,715] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.126 seconds
[2021-12-06 23:07:28,916] {processor.py:163} INFO - Started process (PID=1792) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:07:28,918] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:07:28,920] {logging_mixin.py:109} INFO - [2021-12-06 23:07:28,920] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:07:30,071] {logging_mixin.py:109} INFO - [2021-12-06 23:07:30,058] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:07:30,098] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:07:30,109] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.199 seconds
[2021-12-06 23:08:00,253] {processor.py:163} INFO - Started process (PID=1819) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:08:00,256] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:08:00,259] {logging_mixin.py:109} INFO - [2021-12-06 23:08:00,258] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:08:01,386] {logging_mixin.py:109} INFO - [2021-12-06 23:08:01,376] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:08:01,408] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:08:01,425] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.181 seconds
[2021-12-06 23:08:31,628] {processor.py:163} INFO - Started process (PID=1848) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:08:31,631] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:08:31,633] {logging_mixin.py:109} INFO - [2021-12-06 23:08:31,633] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:08:32,940] {logging_mixin.py:109} INFO - [2021-12-06 23:08:32,930] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:08:32,965] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:08:32,986] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.367 seconds
[2021-12-06 23:09:03,185] {processor.py:163} INFO - Started process (PID=1877) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:09:03,188] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:09:03,189] {logging_mixin.py:109} INFO - [2021-12-06 23:09:03,189] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:09:04,253] {logging_mixin.py:109} INFO - [2021-12-06 23:09:04,237] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:09:04,280] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:09:04,300] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.121 seconds
[2021-12-06 23:09:34,439] {processor.py:163} INFO - Started process (PID=1905) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:09:34,445] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:09:34,448] {logging_mixin.py:109} INFO - [2021-12-06 23:09:34,447] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:09:35,705] {logging_mixin.py:109} INFO - [2021-12-06 23:09:35,692] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:09:35,734] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:09:35,755] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.323 seconds
[2021-12-06 23:10:05,973] {processor.py:163} INFO - Started process (PID=1933) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:10:05,977] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:10:05,979] {logging_mixin.py:109} INFO - [2021-12-06 23:10:05,979] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:10:07,227] {logging_mixin.py:109} INFO - [2021-12-06 23:10:07,201] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:10:07,274] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:10:07,301] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.335 seconds
[2021-12-06 23:10:37,531] {processor.py:163} INFO - Started process (PID=1962) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:10:37,534] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:10:37,536] {logging_mixin.py:109} INFO - [2021-12-06 23:10:37,536] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:10:39,013] {logging_mixin.py:109} INFO - [2021-12-06 23:10:38,995] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:10:39,058] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:10:39,093] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.568 seconds
[2021-12-06 23:11:09,365] {processor.py:163} INFO - Started process (PID=1990) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:11:09,368] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:11:09,372] {logging_mixin.py:109} INFO - [2021-12-06 23:11:09,371] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:11:10,660] {logging_mixin.py:109} INFO - [2021-12-06 23:11:10,647] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:11:10,684] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:11:10,704] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 1.354 seconds
[2021-12-06 23:45:25,052] {processor.py:163} INFO - Started process (PID=2018) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:45:25,054] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:45:25,066] {logging_mixin.py:109} INFO - [2021-12-06 23:45:25,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:45:29,630] {logging_mixin.py:109} INFO - [2021-12-06 23:45:29,534] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:45:29,733] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:45:29,782] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 4.734 seconds
[2021-12-06 23:46:00,390] {processor.py:163} INFO - Started process (PID=2048) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:46:00,399] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:46:00,403] {logging_mixin.py:109} INFO - [2021-12-06 23:46:00,402] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:46:01,145] {logging_mixin.py:109} INFO - [2021-12-06 23:46:01,135] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:46:01,162] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:46:01,171] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.793 seconds
[2021-12-06 23:46:31,341] {processor.py:163} INFO - Started process (PID=2085) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:46:31,342] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:46:31,343] {logging_mixin.py:109} INFO - [2021-12-06 23:46:31,343] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:46:31,949] {logging_mixin.py:109} INFO - [2021-12-06 23:46:31,941] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:46:31,963] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:46:31,970] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.632 seconds
[2021-12-06 23:47:02,127] {processor.py:163} INFO - Started process (PID=2113) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:47:02,128] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:47:02,129] {logging_mixin.py:109} INFO - [2021-12-06 23:47:02,129] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:47:02,723] {logging_mixin.py:109} INFO - [2021-12-06 23:47:02,712] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:47:02,739] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:47:02,757] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.633 seconds
[2021-12-06 23:47:32,981] {processor.py:163} INFO - Started process (PID=2151) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:47:32,982] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:47:32,983] {logging_mixin.py:109} INFO - [2021-12-06 23:47:32,983] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:47:33,604] {logging_mixin.py:109} INFO - [2021-12-06 23:47:33,597] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:47:33,618] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:47:33,632] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.655 seconds
[2021-12-06 23:48:03,864] {processor.py:163} INFO - Started process (PID=2180) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:48:03,869] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:48:03,871] {logging_mixin.py:109} INFO - [2021-12-06 23:48:03,871] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:48:04,494] {logging_mixin.py:109} INFO - [2021-12-06 23:48:04,484] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:48:04,510] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:48:04,521] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.672 seconds
[2021-12-06 23:48:34,566] {processor.py:163} INFO - Started process (PID=2217) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:48:34,567] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:48:34,568] {logging_mixin.py:109} INFO - [2021-12-06 23:48:34,568] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:48:35,177] {logging_mixin.py:109} INFO - [2021-12-06 23:48:35,166] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:48:35,193] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:48:35,207] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.645 seconds
[2021-12-06 23:49:05,365] {processor.py:163} INFO - Started process (PID=2244) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:49:05,367] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:49:05,368] {logging_mixin.py:109} INFO - [2021-12-06 23:49:05,368] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:49:06,026] {logging_mixin.py:109} INFO - [2021-12-06 23:49:06,016] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:49:06,040] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:49:06,047] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.685 seconds
[2021-12-06 23:49:36,186] {processor.py:163} INFO - Started process (PID=2282) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:49:36,187] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:49:36,188] {logging_mixin.py:109} INFO - [2021-12-06 23:49:36,188] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:49:36,866] {logging_mixin.py:109} INFO - [2021-12-06 23:49:36,858] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:49:36,880] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:49:36,886] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.704 seconds
[2021-12-06 23:50:07,063] {processor.py:163} INFO - Started process (PID=2309) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:50:07,065] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:50:07,066] {logging_mixin.py:109} INFO - [2021-12-06 23:50:07,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:50:07,731] {logging_mixin.py:109} INFO - [2021-12-06 23:50:07,725] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:50:07,744] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:50:07,750] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.691 seconds
[2021-12-06 23:50:37,974] {processor.py:163} INFO - Started process (PID=2345) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:50:37,975] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:50:37,976] {logging_mixin.py:109} INFO - [2021-12-06 23:50:37,976] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:50:38,695] {logging_mixin.py:109} INFO - [2021-12-06 23:50:38,688] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:50:38,712] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:50:38,720] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.750 seconds
[2021-12-06 23:51:08,913] {processor.py:163} INFO - Started process (PID=2373) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:51:08,914] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:51:08,915] {logging_mixin.py:109} INFO - [2021-12-06 23:51:08,915] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:51:09,647] {logging_mixin.py:109} INFO - [2021-12-06 23:51:09,639] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:51:09,662] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:51:09,668] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.759 seconds
[2021-12-06 23:51:39,851] {processor.py:163} INFO - Started process (PID=2410) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:51:39,852] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:51:39,853] {logging_mixin.py:109} INFO - [2021-12-06 23:51:39,853] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:51:40,488] {logging_mixin.py:109} INFO - [2021-12-06 23:51:40,483] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:51:40,501] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:51:40,507] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.659 seconds
[2021-12-06 23:52:10,702] {processor.py:163} INFO - Started process (PID=2438) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:52:10,704] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:52:10,705] {logging_mixin.py:109} INFO - [2021-12-06 23:52:10,705] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:52:11,284] {logging_mixin.py:109} INFO - [2021-12-06 23:52:11,275] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:52:11,301] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:52:11,308] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.611 seconds
[2021-12-06 23:52:41,468] {processor.py:163} INFO - Started process (PID=2476) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:52:41,470] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:52:41,471] {logging_mixin.py:109} INFO - [2021-12-06 23:52:41,471] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:52:42,128] {logging_mixin.py:109} INFO - [2021-12-06 23:52:42,123] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:52:42,141] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:52:42,148] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.683 seconds
[2021-12-06 23:53:12,347] {processor.py:163} INFO - Started process (PID=2504) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:53:12,348] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:53:12,349] {logging_mixin.py:109} INFO - [2021-12-06 23:53:12,349] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:53:12,975] {logging_mixin.py:109} INFO - [2021-12-06 23:53:12,970] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:53:12,987] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:53:12,994] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.650 seconds
[2021-12-06 23:53:43,162] {processor.py:163} INFO - Started process (PID=2543) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:53:43,164] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:53:43,165] {logging_mixin.py:109} INFO - [2021-12-06 23:53:43,165] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:53:43,811] {logging_mixin.py:109} INFO - [2021-12-06 23:53:43,806] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:53:43,825] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:53:43,835] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.676 seconds
[2021-12-06 23:54:14,003] {processor.py:163} INFO - Started process (PID=2571) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:54:14,005] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:54:14,006] {logging_mixin.py:109} INFO - [2021-12-06 23:54:14,006] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:54:14,681] {logging_mixin.py:109} INFO - [2021-12-06 23:54:14,673] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:54:14,696] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:54:14,706] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.706 seconds
[2021-12-06 23:54:44,780] {processor.py:163} INFO - Started process (PID=2608) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:54:44,782] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:54:44,783] {logging_mixin.py:109} INFO - [2021-12-06 23:54:44,783] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:54:45,436] {logging_mixin.py:109} INFO - [2021-12-06 23:54:45,429] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:54:45,454] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:54:45,463] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.688 seconds
[2021-12-06 23:55:16,123] {processor.py:163} INFO - Started process (PID=2636) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:55:16,124] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:55:16,124] {logging_mixin.py:109} INFO - [2021-12-06 23:55:16,124] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:55:16,765] {logging_mixin.py:109} INFO - [2021-12-06 23:55:16,758] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:55:16,786] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:55:16,799] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.679 seconds
[2021-12-06 23:55:46,950] {processor.py:163} INFO - Started process (PID=2673) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:55:46,952] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:55:46,953] {logging_mixin.py:109} INFO - [2021-12-06 23:55:46,952] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:55:47,609] {logging_mixin.py:109} INFO - [2021-12-06 23:55:47,598] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:55:47,624] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:55:47,633] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.687 seconds
[2021-12-06 23:56:17,864] {processor.py:163} INFO - Started process (PID=2702) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:56:17,867] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:56:17,870] {logging_mixin.py:109} INFO - [2021-12-06 23:56:17,869] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:56:18,496] {logging_mixin.py:109} INFO - [2021-12-06 23:56:18,485] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:56:18,510] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:56:18,518] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.668 seconds
[2021-12-06 23:56:48,644] {processor.py:163} INFO - Started process (PID=2740) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:56:48,646] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:56:48,646] {logging_mixin.py:109} INFO - [2021-12-06 23:56:48,646] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:56:49,299] {logging_mixin.py:109} INFO - [2021-12-06 23:56:49,292] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:56:49,312] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:56:49,319] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.678 seconds
[2021-12-06 23:57:19,495] {processor.py:163} INFO - Started process (PID=2769) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:57:19,496] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:57:19,497] {logging_mixin.py:109} INFO - [2021-12-06 23:57:19,497] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:57:20,101] {logging_mixin.py:109} INFO - [2021-12-06 23:57:20,091] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:57:20,117] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:57:20,125] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.634 seconds
[2021-12-06 23:57:50,283] {processor.py:163} INFO - Started process (PID=2806) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:57:50,284] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:57:50,285] {logging_mixin.py:109} INFO - [2021-12-06 23:57:50,285] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:57:50,977] {logging_mixin.py:109} INFO - [2021-12-06 23:57:50,969] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:57:50,991] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:57:51,000] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.721 seconds
[2021-12-06 23:58:21,162] {processor.py:163} INFO - Started process (PID=2833) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:58:21,164] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:58:21,165] {logging_mixin.py:109} INFO - [2021-12-06 23:58:21,164] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:58:21,761] {logging_mixin.py:109} INFO - [2021-12-06 23:58:21,754] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:58:21,777] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:58:21,784] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.625 seconds
[2021-12-06 23:58:51,943] {processor.py:163} INFO - Started process (PID=2870) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:58:51,944] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:58:51,946] {logging_mixin.py:109} INFO - [2021-12-06 23:58:51,946] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:58:52,565] {logging_mixin.py:109} INFO - [2021-12-06 23:58:52,557] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:58:52,579] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:58:52,587] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.649 seconds
[2021-12-06 23:59:22,739] {processor.py:163} INFO - Started process (PID=2898) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:59:22,740] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:59:22,741] {logging_mixin.py:109} INFO - [2021-12-06 23:59:22,741] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:59:23,333] {logging_mixin.py:109} INFO - [2021-12-06 23:59:23,326] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:59:23,349] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:59:23,358] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.623 seconds
[2021-12-06 23:59:53,519] {processor.py:163} INFO - Started process (PID=2936) to work on /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:59:53,520] {processor.py:625} INFO - Processing file /opt/airflow/dags/VegasPipeline/__init__.py for tasks to queue
[2021-12-06 23:59:53,521] {logging_mixin.py:109} INFO - [2021-12-06 23:59:53,521] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:59:54,183] {logging_mixin.py:109} INFO - [2021-12-06 23:59:54,177] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/VegasPipeline/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/VegasPipeline/__init__.py", line 6, in <module>
    from pipeline_tools import run_transform_gbq
  File "/opt/airflow/plugins/pipeline_tools.py", line 4, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
[2021-12-06 23:59:54,198] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/VegasPipeline/__init__.py
[2021-12-06 23:59:54,204] {processor.py:171} INFO - Processing /opt/airflow/dags/VegasPipeline/__init__.py took 0.689 seconds
